image: ubuntu/latest
sources:
- https://git.sr.ht/~tsileo/blobstash
packages:
- python3-dev
- python3-pip
tasks:
- setup: |
   mkdir go
   export GOPATH=/home/build/go
   wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
   sudo tar -C /usr/local -xzf go1.13.4.linux-amd64.tar.gz
   pip3 install git+https://github.com/tsileo/blobstash-python.git
- test: |
   export GOPATH=/home/build/go
   cd blobstash
   /usr/local/go/bin/go install -mod=vendor
   /usr/local/go/bin/go test -v -mod=vendor ./...
   export PATH=$PATH:$GOPATH/bin/
   python3 integration_tests/docstore.py
