---
kind: pipeline
name: default
steps:
  - name: build_and_test
    image: golang:latest
    commands:
      - go install -mod=vendor
      - mv -r $GOPATH/bin/blobstash /usr/local/bin/blobstash
      - go test -v -mod=vendor ./...

  - name: integration_test
    image: python:3
    commands:
      - pip install git+https://github.com/tsileo/blobstash-python.git
      # FIXME(tsileo): import the new tests from blobstash-base
      # - python3 integration_tests/blobstore_kvstore.py
      - python3 integration_tests/docstore.py
---
kind: signature
hmac: 8e7bc895e96b7b1982933dff475c9dedae044b3fbd71e68b97846be7bce7bf05

...
