---
kind: pipeline
name: default
steps:
  # Build the blobstash binary
  - name: build
    image: golang:latest
    commands:
      - go install -mod=vendor
      - mkdir bin
      - cp -r $GOPATH/bin/blobstash bin/blobstash

  # Run the unit test suite
  - name: test
    image: golang:latest
    commands:
      - go test -v -mod=vendor ./...


  # Integration tests against a running instance with blobstash-python
  - name: integration_test
    image: python:3
    commands:
      - pip install git+https://github.com/tsileo/blobstash-python.git
      # FIXME(tsileo): import the new tests from blobstash-base
      # - python3 integration_tests/blobstore_kvstore.py

      # Add blobstash the PATH before we can run the tests
      - export PATH=$PATH:`pwd`/bin
      - python3 integration_tests/docstore.py
---
kind: signature
hmac: 051666378d265eae7935375e2dd8fd1f3da93358131f246a11a4c72c59786287

...
