---
kind: pipeline
name: default
steps:
  - name: build_and_test
    image: golang:latest
    commands:
      - go install -mod=vendor
      - mkdir bin
      - cp -r $GOPATH/bin/blobstash bin/blobstash
      # - go test -v -mod=vendor ./...

  - name: integration_test
    image: python:3
    commands:
      - pip install git+https://github.com/tsileo/blobstash-python.git
      # FIXME(tsileo): import the new tests from blobstash-base
      # - python3 integration_tests/blobstore_kvstore.py
      - export PATH=$PATH:`pwd`/bin
      - python3 integration_tests/docstore.py
---
kind: signature
hmac: 332893c5a57b52a018694d13719302e997da0c5a601ca1df6e0dddd42f62b850

...
