author: Thomas Sileo
description: BlobStash
os: darwin linux
includes:
  - README.md
  - LICENSE
  - conf
  - templates
  - public
  - static
  - views
excludes:
  - \.git
script:
  - go get -v
  - go build
