language: go
go:
- 1.9
install: true
script:
# Install Python3 (Anaconda looks like the easiest way in Travis)
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
- bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- pip install requests
# Run golang unit tests
- go get -v a4.io/blobstash/...
- cd $GOPATH/src/a4.io/blobstash
- go test $(go list ./... | grep pkg)
# Cross compile script
# FIXME(tsileo): re-enable the cross compile
# - ./extras/cross_compile.sh
# Run the integrations tests
- go build blobstash.go
- pip install git+https://github.com/tsileo/blobstash-python-base.git
- pip install git+https://github.com/tsileo/blobstash-python-filetree.git
- pip install git+https://github.com/tsileo/blobstash-python-docstore.git
# FIXME(tsileo): import the new tests from blobstash-base
# - python3 integration_tests/blobstore_kvstore.py
- python3 integration_tests/docstore.py
deploy:
  provider: releases
  api_key:
    secure: iWV46e1ZV5rrQOogkp4MQvs7qycWcvWHRlXcWSaCukigsAWXUoWebEAsUXEc+81vNQQYY7gUWsUss5kRObhutR0eYSGwLEZAps84hOZM6WeKZyzt8eARH+z11C1+zTZdan8+wNp0hMu+lYR/7XCrJkWpbt2Swvm0furJCFfz12Z6XjHhsUMUAbdU2Kj4bV4dxn/nuCzhK3OxIa6rfa8X/cmQu6HABYXsJDRg1nmGmFLpoHHR44oi9562CuTmgGK1HaicppqTPMP6Dxx0MEmItCxX2GZ2cHtSZTDDw8I4lRX05kaAc/HZMOjWtIDP4WbMQaPCpN5YSt2+/ap4rM8ILoz6oMWhcQGzbVpgiwb4GcogOP72rq/HzZZeB36lCq8ojuqtAwbdFqm94twHX3CcO09Vnhpx8YKVUwxyvZsKcjriDU6oEq4d/rCagzx3Y4TUlhNIw4WAxodhTc0/95s7kcAcvxuzHdClj9jWAWmTwTDcMmh1BIrTEarXMVFS91IkQFFiJY3TJc3CXrqaLvV0j4Fk7KLOjzRP60g8Oe/ozLAu49zgszLvaXSuw5apUB4Hdb1iOd3khiRy7kp1DsoTTOSqnwlGURx2weDo5UtyT5etYvA3kfFJTIDkduLJf9oCEXHvzQhzSogU9eSKWzT56dxqfQ3unwe6offCWL9xpQQ=
  file:
    - releases/blobstash-darwin-amd64
    - releases/blobstash-freebsd-amd64
    - releases/blobstash-linux-amd64
    - releases/blobstash-linux-arm
    - releases/blobstash-linux-mipsle
  skip_cleanup: true
  on:
    tags: true
