# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "a4.io/blobsfile"

[[constraint]]
  branch = "master"
  name = "a4.io/gluapp"

[[constraint]]
  branch = "master"
  name = "a4.io/gluarequire2"

[[constraint]]
  name = "github.com/Workiva/go-datastructures"
  version = "1.0.43"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.56"

[[constraint]]
  branch = "master"
  name = "github.com/blevesearch/segment"

[[constraint]]
  branch = "master"
  name = "github.com/carbocation/interpose"

[[constraint]]
  branch = "master"
  name = "github.com/cznic/kv"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/blake2b"

[[constraint]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/hanwen/go-fuse"
  version = "20170619.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  name = "github.com/reiver/go-porterstemmer"
  version = "1.0.1"

[[constraint]]
  name = "github.com/restic/chunker"
  version = "0.2.0"

[[constraint]]
  branch = "go1"
  name = "github.com/rwcarlsen/goexif"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "3.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/yuin/gopher-lua"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/inconshreveable/log15.v2"
  version = "2.13.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
